"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { detectLanguage, isLangCode, type LangCode } from "./language-detect";
import { toSpeakable } from "./speech-text";

interface UseTextToSpeechResult {
  /** Index of the message currently loading audio (server path only), or null. */
  loadingId: number | null;
  /** Index of the message currently playing, or null. */
  playingId: number | null;
  error: string | null;
  /** Speak a message; tapping the same one again stops it. */
  speak: (id: number, text: string, language?: string) => Promise<void>;
  stop: () => void;
}

/** BCP-47 tag for the browser speech engine. */
function toBCP47(code: LangCode): string {
  switch (code) {
    case "yo":
      return "yo-NG";
    case "ig":
      return "ig-NG";
    case "ha":
      return "ha-NG";
    default:
      return "en-NG";
  }
}

function getSynth(): SpeechSynthesis | null {
  return typeof window !== "undefined" && "speechSynthesis" in window
    ? window.speechSynthesis
    : null;
}

interface Capabilities {
  intron: boolean;
  yarngpt: boolean;
}

let capabilities: Promise<Capabilities> | null = null;
function loadCapabilities(): Promise<Capabilities> {
  if (!capabilities) {
    capabilities = fetch("/api/speak")
      .then((r) => (r.ok ? r.json() : null))
      .then((d) => ({ intron: !!d?.intron, yarngpt: !!d?.yarngpt }))
      .catch(() => {
        capabilities = null; // retry next time
        return { intron: false, yarngpt: false };
      });
  }
  return capabilities;
}

/**
 * Text-to-speech for assistant replies.
 *
 *  1. Intron (server) when configured — native Yoruba, Igbo, Hausa, Pidgin and
 *     Nigerian-accented English voices.
 *  2. The browser's speechSynthesis — instant and free, but its Nigerian
 *     language voices are limited.
 *  3. The YarnGPT service, when the browser has no speech synthesis.
 */
export function useTextToSpeech(): UseTextToSpeechResult {
  const [loadingId, setLoadingId] = useState<number | null>(null);
  const [playingId, setPlayingId] = useState<number | null>(null);
  const [error, setError] = useState<string | null>(null);

  const audioRef = useRef<HTMLAudioElement | null>(null);
  const urlRef = useRef<string | null>(null);
  // Bumped on every stop/speak so a slow response can't start playing late.
  const requestRef = useRef(0);

  const cleanupAudio = useCallback(() => {
    const a = audioRef.current;
    if (a) {
      a.onended = null;
      a.onerror = null;
      a.pause();
      a.removeAttribute("src");
      a.load();
      audioRef.current = null;
    }
    if (urlRef.current) {
      URL.revokeObjectURL(urlRef.current);
      urlRef.current = null;
    }
  }, []);

  const stop = useCallback(() => {
    requestRef.current++;
    getSynth()?.cancel();
    cleanupAudio();
    setPlayingId(null);
    setLoadingId(null);
  }, [cleanupAudio]);

  /** Play audio generated by /api/speak. Resolves false if it failed. */
  const speakServer = useCallback(
    async (id: number, text: string, language: LangCode): Promise<boolean> => {
      const request = ++requestRef.current;
      setLoadingId(id);
      try {
        const res = await fetch("/api/speak", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ text, language }),
        });
        if (!res.ok) {
          const data = await res.json().catch(() => ({}));
          throw new Error(data.error || `Speech failed (${res.status})`);
        }
        const blob = await res.blob();
        if (request !== requestRef.current) return true; // superseded by another tap

        const url = URL.createObjectURL(blob);
        urlRef.current = url;
        const audio = new Audio(url);
        audioRef.current = audio;
        audio.onended = () => {
          cleanupAudio();
          setPlayingId(null);
        };
        audio.onerror = () => {
          setError("Couldn't play audio.");
          cleanupAudio();
          setPlayingId(null);
        };
        await audio.play();
        setPlayingId(id);
        return true;
      } catch (e) {
        if (request === requestRef.current) {
          setError((e as Error).message || "Text-to-speech failed.");
        }
        return false;
      } finally {
        if (request === requestRef.current) setLoadingId(null);
      }
    },
    [cleanupAudio]
  );

  /** Speak with the browser's voice. Returns false if unavailable. */
  const speakBrowser = useCallback((id: number, text: string, language: LangCode): boolean => {
    const synth = getSynth();
    if (!synth) return false;
    const u = new SpeechSynthesisUtterance(toSpeakable(text));
    u.lang = toBCP47(language);
    const voices = synth.getVoices();
    const voice =
      voices.find((v) => v.lang === u.lang) ||
      voices.find((v) => v.lang?.startsWith("en-NG")) ||
      voices.find((v) => v.lang?.startsWith("en"));
    if (voice) u.voice = voice;
    const done = () => setPlayingId((cur) => (cur === id ? null : cur));
    u.onend = done;
    u.onerror = done;
    synth.cancel();
    synth.speak(u);
    setPlayingId(id);
    return true;
  }, []);

  const speak = useCallback(
    async (id: number, text: string, language?: string) => {
      // Tapping the active message again toggles it off.
      if (playingId === id || loadingId === id) {
        stop();
        return;
      }
      stop();
      setError(null);

      const lang: LangCode = isLangCode(language) ? language : detectLanguage(text).code;
      const caps = await loadCapabilities();

      if (caps.intron) {
        if (await speakServer(id, text, lang)) return;
        // Intron failed: the browser voice is better than silence.
        if (speakBrowser(id, text, lang)) setError(null);
        return;
      }
      if (speakBrowser(id, text, lang)) return;
      if (caps.yarngpt) {
        await speakServer(id, text, lang);
        return;
      }
      setError("Text-to-speech isn't available in this browser.");
    },
    [playingId, loadingId, stop, speakServer, speakBrowser]
  );

  useEffect(() => {
    return () => {
      getSynth()?.cancel();
      cleanupAudio();
    };
  }, [cleanupAudio]);

  return { loadingId, playingId, error, speak, stop };
}
